language: node_js
node_js:
  - "12.14.1"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - echo "Deploying!"
  - npm test
  - npm run build
install:
  - npm install
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN